### ISSUE TITLE
Intergration

### ISSUE THREAD

**Issue by vincentbii** [knox2/Pesapal#13]
I have issues integrating with my site. How can I get your help. The information given is incomplete

**Comment by knox2** [comment]
whats the issue

**Comment by murwa** [comment]
@vincentbii what issues?

**Comment by vincentbii** [comment]
Please give me more information on integration. I don't know how to go
about it

Kind Regards
Vincent Bii
Call /text /whatsapp - 0711195921

**Comment by knox2** [comment]
@vincentbii have you tried following the documentation

**Comment by vincentbii** [comment]
Timothy, which document? You haven't attached.

Thanks
Kind regards,
Vincent Bii
Tel:254 711 195 921

**Comment by knox2** [comment]
https://github.com/knox2/Pesapal/blob/master/README.md

**Comment by vincentbii** [comment]
Thanks Timothy. I published the package configuration, and that is where I
am stack. After publishing, what next?

Thanks
Kind regards,
Vincent Bii
Tel:254 711 195 921

**Comment by knox2** [comment]
After that, just set up the .env variables and follow the example given (the Controller, Routes)

**Comment by vincentbii** [comment]
Thanks, let me check on it

Thanks
Kind regards,
Vincent Bii
Tel:254 711 195 921

**Comment by vincentbii** [comment]
It means I have to create my owns views for making payments and to view
transaction details

Thanks
Kind regards,
Vincent Bii
Tel:254 711 195 921

**Comment by knox2** [comment]
yes
