### ISSUE TITLE
IPN

### ISSUE THREAD

**Issue by vkyeswa** [knox2/Pesapal#14]
Which method am I to use, redirectToIPN or getMerchantStatus? Am failing to get notification updates to my Model...still using the demo.pesapal site. Thank you

**Comment by murwa** [comment]
I don't think demo.pesapal has IPN support

**Comment by knox2** [comment]
@murwa there is a IPN page at demo,i dont know if it works, @vkyeswa which url are you using as your IPN

**Comment by vkyeswa** [comment]
By url do you mean domain.com/paymentsconfirmation?

**Comment by knox2** [comment]
@vkyeswa  yes, so u used domain.com/paymentsconfirmation? if so, let me have a look at your routes file related to pesapal

**Comment by vkyeswa** [comment]
Will do that as soon as i get to access to my computer

**Comment by vkyeswa** [comment]
`Route::group(['prefix' => 'subscription'], function () {
  //PESAPAL
  Route::get('donepayment', 'PaymentsController@paymentsuccess')->name('paymentsuccess');
  Route::get('paymentconfirmation', 'PaymentsController@paymentconfirmation');
});`

**Comment by vkyeswa** [comment]
basically its more like the one you have in your example

**Comment by knox2** [comment]
u do have a prefix in your routes so the ipn should be domain.com/subscription/paymentsconfirmation

**Comment by vkyeswa** [comment]
that is what i did for my IPN Listener URL and exempted my subscription url from the CsrfVer... middleware. An there is no way of testing if the IPN listener attempt was successful... i guess will have to try it out with a fully registered pesapal account

**Comment by murwa** [comment]
@vkyeswa are you able to create a payment on the sandbox? If so, does sandbox process your payments?

**Comment by vkyeswa** [comment]
yep, my payments using the demo testing transactions are reflected and show as completed in the sandbox...but i can't read the status from my paymentconfirmation route which i registered in the IPN listener...so my db still has the status=PENDING

**Comment by murwa** [comment]
Try it out with a live payment then. Your routing code is fine...where's u dev? Are u using localhost?

**Comment by vkyeswa** [comment]
will try it out with a live payment...testing from demo servers (online)...will let you know

**Comment by vkyeswa** [comment]
finally got this working...had to retry the Merchant IPN (Instant Payment Notification) Settings in demo but for a live system. it works fine.
