### ISSUE TITLE
Pesapal Confirmation Status

### ISSUE THREAD

**Issue by vincentbii** [knox2/Pesapal#15]
Hi guys.
I have successfully integrated this API in my site. In addition to this, I need to get the amount paid by a client when I request for payment confirmation. Currently, I only get the status of the transaction of which the status will still be pending if one pays an amount less or more than what the iframe  gets from my payment form. 
Can someone help me solve this.

Kind Regards

**Comment by murwa** [comment]
From what I know, the transaction will not be processed if the amount paid doesn't match the amount supplied. If u have anything beyond that, let me know!
