### ISSUE TITLE
Please assist

### ISSUE THREAD

**Issue by frankleenDev** [knox2/Pesapal#16]
This will be very useful however some of us a very new to laravel. Like I am torn a bit on where to allocate all these files, I know only a few.

**Comment by murwa** [comment]
Where exactly are you stuck, @frankleenDev?

**Comment by frankleenDev** [comment]
Also I have an error in Pesapal.php exception. call back route doesn't exist..

From the Pesapal.php
 $params = array_merge($defaults, $params);

        if (!config('pesapal.callback_route')) {
            throw new PesapalException("callback route not provided");
        } else {
            if (!Route::has(config('pesapal.callback_route'))) {
                throw new PesapalException("callback route does not exist");
            }
        }

From routes in knox
<?php

Route::get('{$event_id}/pesament/create?is_embedded=0#order_form',
	['as'=>'pesapal-callback', 
	'uses'=>'Knox\Pesapal\PesapalAPIController@handleCallback']);

Route::get('pesapal-ipn', ['as'=>'pesapal-ipn', 
	'uses'=>'Knox\Pesapal\PesapalAPIController@handleIPN']);

?>

![pesapalexception](https://user-images.githubusercontent.com/29050725/35374779-660316e4-01b5-11e8-9e3e-1c14f3b46ed1.png)

**Comment by murwa** [comment]
What version of laravel are you using?

**Comment by frankleenDev** [comment]
Laravel 5

**Comment by frankleenDev** [comment]
I set all the files to public then I ran the instructions biggest concern was could not find most of the pelapal controller kept saying it didn't exist

**Comment by murwa** [comment]
You need to define both `PESAPAL_CALLBACK_ROUTE ` and `PESAPAL_IPN` on your controller, then link them on the given keys in your .env

**Comment by frankleenDev** [comment]
There is already a class that has those variable and I've defined them in the enviroments file isn't it enough to just use class_name in my controller...

**Comment by murwa** [comment]
Which class?

**Comment by frankleenDev** [comment]
Sorry I meant in the packages congig we have pesapal.php anyway I have a new error....
![new](https://user-images.githubusercontent.com/29050725/35382317-e35530c2-01cf-11e8-8247-8f3cface6f5d.png)


Source:
![237](https://user-images.githubusercontent.com/29050725/35382363-0e982dac-01d0-11e8-8355-2d25fd98f076.png)

**Comment by murwa** [comment]
Share your pesapal.php

**Comment by frankleenDev** [comment]
<?php

return [
    /*
     * Pesapal consumer key
     */
    'consumer_key'    => env('PESAPAL_CONSUMER_KEY'),

    /*
     * Pesapal consumer secret
     */
    'consumer_secret' => env('PESAPAL_CONSUMER_SECRET'),

    /*
     * ISO code for the currency
     */
    'currency'        => env('PESAPAL_CURRENCY', 'TZS'),

    /*
     * controller method to call for instant notifications IPN as relative path from App\Http\Controllers\
     * eg "TransactionController@confirmation"
     */
    'ipn'             => env('PESAPAL_IPN'),

    /*
     * Pesapal environment
     */
    'live'            => env('PESAPAL_LIVE', false),

    /*
     * Route name to handle the callback
     * eg Route::get('donepayment', ['as' => 'paymentsuccess', 'uses'=>'PaymentsController@paymentsuccess']);
     * The route name is "paymentsuccess"
     */
    'callback_route'  => env('PESAPAL_CALLBACK_ROUTE'),

];


![pesapal](https://user-images.githubusercontent.com/29050725/35385673-2a11829a-01da-11e8-84b4-d99d628ac361.png)

**Comment by murwa** [comment]
what are your values for `PESAPAL_IPN ` and `PESAPAL_CALLBACK_ROUTE ` in your .env?

**Comment by frankleenDev** [comment]
PESAPAL_IPN=PesapalAPIController@handleIPN

PESAPAL_CALLBACK_ROUTE=paymentSuccess

**Comment by murwa** [comment]
Do you have the route `paymentSuccess` defined? Also, is the `PesapalAPIController@handleIPN` your controller? This package doesn't handle IPN and callbacks for you. That's your work. Provide that in a controller and provide them as explained in the readme.

**Comment by murwa** [comment]
I've made a simple sample project to demo what u need. Kindly check it out [here](https://github.com/murwa/pesapal-sample). Open an issue on the repo if you have any issues

**Comment by felixkaleke** [comment]
Knox\Pesapal\Exceptions\PesapalException
callback route not provided,

this is the error am experiencing

**Comment by frankleenDev** [comment]
Hello, I have a delivery software that is both on web and android I want to
implement a payment system like the one in betpawa can you do it.
