### ISSUE TITLE
Incomplete documentation

### ISSUE THREAD

**Issue by bryosabian** [knox2/Pesapal#18]
Thank you for the awesome Laravel 5 module.

I'd really like to know how does one implement the Pesapal payment gateway view using the values returned by Pesapal::makePayment($details) function?

Also what ENV variables should I use to define whether the integration is a live or demo environment? It's not provided.

**Comment by murwa** [comment]
`Pesapal::makePayment($details)` returns an iFrame. Embed it in your views.

> Also what ENV variables should I use to define whether the integration is a live or demo environment? It's not provided.

Kindly go through the doc

`PESAPAL_LIVE=true`

Set false for development.

**Comment by bryosabian** [comment]
Awesome. Thanks. Went through the doc. Couldn't find anything. Probably I didn't look well. Thanks for the module.
