### ISSUE TITLE
Can we add this payment gatway in 'Attendize' apllication?

### ISSUE THREAD

**Issue by kuldeepJain11** [knox2/Pesapal#19]
Hello, 

I want to integrate 'Pesapal' payment gatway in application 'Attendize'. you can check it from 'https://www.attendize.com/'. Can you please guid me how can i integrate in it. 

Thanks,

**Comment by knox2** [comment]
Have you tried following the documentation? It would be easier to get help on where specifically you are getting stuck

**Comment by aviary48** [comment]
how to display the iframe on the view

**Comment by aviary48** [comment]
so many questions, 
where do i place the link to post my form to pesapal,
how do i display the iframe on my view? for instance on the checkout pag,
how do i know i have posted to pesapal? 
i've followed the documentation to the latter and i don't know how this works.

**Comment by knox2** [comment]
Closing this with No reply from user

**Comment by silicon755** [comment]
Hello @knox2 , I have tried the documentation but I don't seem to get the hang of it. Any way you can help?

**Comment by knox2** [comment]
Hello @silicon755 Are you trying to integrate into the attendize app?

**Comment by silicon755** [comment]
Yes that's what I am trying to achieve, any idea on how to go about it ?

**Comment by knox2** [comment]
I haven't used that application, are you getting any errors?

**Comment by silicon755** [comment]
Yes I bumped into few errors, will post a screenshot of the same here tomorrow morning
