### ISSUE TITLE
IPN

### ISSUE THREAD

**Issue by maxwellmandela** [knox2/Pesapal#2]
Hi, could you help me get around getting ipn up? I keep getting bad method error, is it because my ipn in .env is 'getstatus' while my ipn url in the dashbboard is 'localhost:8000/paymentsuccess'

**Comment by knox2** [comment]
The PESAPAL_IPN in .env should be YourController@getstatus

**Comment by barmao** [comment]
@knox2 hey man, a little assistance here. I need to resize it

**Comment by knox2** [comment]
just pass the width and height to the array

```
$details = array(
        'amount' => $payments -> amount,
        'description' => 'Test',
        'type' => 'MERCHANT',
        'first_name' => 'John',
        'last_name' => 'Doe',
        'email' => 'johndoe@google.com', 
        'phonenumber' => '254723232323',
        'reference' => $payments -> transaction,
        //'currency' => 'USD',
'width' => '100px',
'height' => '100px'
    );

    return Pesapal::makePayment($details);
```

**Comment by barmao** [comment]
Thanks alot man, cheers.

**Comment by knox2** [comment]
You are welcome
