### ISSUE TITLE
integration

### ISSUE THREAD

**Issue by aviary48** [knox2/Pesapal#20]
how do i display the iframe from pesapal on my view?
how do i know it has posted to pesapal?
where do i place the links that are posting to pesapal?
i've followed the documentation to the latter and i still don't know why it's not working

**Comment by knox2** [comment]
1. You display the iframe as `{{ iframe }}`
2. Pesapal will give feedback on successful transaction, the IPN setup in this package will receive a response from pesapal on successful.
3. Which links?
4. If you follow it correctly it should work

**Comment by aviary48** [comment]
ok i'm using laravel 5.5, i've used {{ $iframe }} its giving me an error on the view, let me post the sample code of how i've done it on  my controller. 
public function postCheckout(Request $request)
   {
       if (!Session::has('cart')) {
           return redirect()->route('pages.cart');
       }
       $oldCart = Session::get('cart');
       $cart = new Cart($oldCart);

       $order = new Order();
       $order->cart = serialize($cart);
       $order->transactionid = Pesapal::random_reference();
       $order->status = 'NEW';
       $order->address = $request->input('address');
       $order->name = $request->input('name');
       $order->phone = $request->input('phone');
       Auth::user()->orders()->save($order);

       $details = array(
           'amount' => $cart->totalPrice + 300, //300 for shipping charges
           'description' => 'test transaction',
           'type' => 'MERCHANT',
           'first_name' => $request->input('first-name'),
           'second_name' => $request->input('name'),
           'email' => $request->input('email'),
           'phonenumber' => $request->input('phone'),
           'reference' => $order->transactionid,
           'height' => '400px',
       );

       //
       $iframe = Pesapal::makePayment($details);
       return view('pages.checkout', ['iframe'=>$iframe]);

on the view
<iframe class="embed-responsive-item" src="{{ $iframe }}" width="100%" height="700px"  scrolling="no" frameBorder="0">  </iframe> 
i get this error "Undefined variable: iframe"

**Comment by knox2** [comment]
You are doing it wrong on the iframe part.

`{{ $iframe }}` already contains the iframe tag with attributes

so replace
`<iframe class="embed-responsive-item" src="{{ $iframe }}" width="100%" height="700px" scrolling="no" frameBorder="0"> </iframe>`
with 
`{{ $iframe }}`

**Comment by aviary48** [comment]
still the same error :| i don't know if there's something i'm missing

**Comment by aviary48** [comment]
alright quick one, when the user has filled in the form with his details and clicks the submit button, does the info go to pesapal first so that they can display the iframe or who does it work?

**Comment by aviary48** [comment]
and then,in my previous implementation i was handling the form submission using js, 
was just wondering if this line handles the form submission or i have to do that as well?
$iframe = Pesapal::makePayment($details);
which is in the controller under the function postcheckout

**Comment by knox2** [comment]
This line 
`$iframe = Pesapal::makePayment($details);`
generates the Iframe element from pesapal with the relevant details like amount and order ID already passed.
The Iframe is displayed so that the user can make payment via pesapal.

You must be passing the data to the wrong view if it says its undefined

**Comment by aviary48** [comment]
is there a specific view that i should be passing the iframe to? in my case i'm returning it to my chekout page where the user has to fill the form for submission

**Comment by knox2** [comment]
No, you can pass to any view

have you tried doing a dd on the controller

**Comment by aviary48** [comment]
hi, there's some progress. i imported the pesapal.php on this project, as in i made a file and imported it to my controller, the iframe is being added to the view but its not being displayed. instead there's this error being displayed 
Problem: parameter_rejected | Advice: invalid_value_amount_exceeds_limit> oauth_parameters_rejected | 1750 
1750 is the amount to be billed to the customer

**Comment by aviary48** [comment]
ok more progress, been able to display the iframe, so let me get this straight, the amount is sent together with the other params to pesapal, then the iframe is displayed to the customer for him to choose payment option and once he has paid i handle the redirect on my end, right? i've read somewhere that the error is brought about by the limit i'm allowed to transact or something, let me copy paste here
"This error means that your account on Pesapal has a limit on the amount it can transact. By default the amount is usually set to USD 10 or the equivalent of it in local currency.

You need to contact the team at support.pesapal.com to complete your sign-up by submitting contract and documents for your business in order to have the account activate for full transactions."

**Comment by knox2** [comment]
That just means that the amount you want to pay passes pesapal's limit. If you are a business and haven't signed a contract with them I believe the limit is Ksh 1000

**Comment by aviary48** [comment]
yes, i'm contacting them about this,
i'm still getting the iframe error not sure if its how i'm handling my routes, it worked yesterday , i was even able to display the form from pesapal. 
But thanks, this worked out!

**Comment by knox2** [comment]
If you input anything less than the limit it should work for now.

**Comment by aviary48** [comment]
is there a reason why the iframe gets displayed at times and at times it doesn't? instead it shows the error Undefined variable: iframe

**Comment by aviary48** [comment]
hi could there bean issue with how the iframe is being returned to the view?? it gets displayed at times it doesnt. I've gone to the point where i have redone the whole thing and changed my logic as well. Any suggestions?

**Comment by knox2** [comment]
**undefined** means its not being passed into the view. I can't really help further without access to your code. The library seems to work bcoz I use it in production and I've never encountered such an error.

**Comment by aviary48** [comment]
give me your email i add you to my reppo in bitbucket then you can view the code if it's ok

**Comment by knox2** [comment]
I did...I'm closing this since its not a lib issue

**Comment by aviary48** [comment]
alright.. tho i didn't get your email

**Comment by knox2** [comment]
Resent to eugenekamadi@yahoo.com
