### ISSUE TITLE
after payment method iframe error on view

### ISSUE THREAD

**Issue by freelancerumesh** [knox2/Pesapal#21]
Problem: parameter_rejected | Advice: unknown_error_occured> oauth_parameters_rejected | request_xml_data
when iframe trying to load
------------
with following detail on Pesapal::makePayment($details);
------------------------
"amount" => "1200"
  "description" => "{"STUD_ID":"1","REG_NO":"STUD-0001","FEE_MASTER_ID":"1","DESCRIPTION":"BBA I-ADMISSION FEE"}"
  "type" => "MERCHANT"
  "first_name" => "UTTAM"
  "last_name" => "YADU"
  "email" => "student@gmail.com"
  "phonenumber" => "977-98989898"
  "reference" => "STUD-0001-1"
  "height" => "400px"
  "currency" => "USD"
---------------

**Comment by knox2** [comment]
Are you allowed by pesapal to transact on that Amount? They usually have limits. Kindly confirm from them

**Comment by knox2** [comment]
No feedback from user, closing this
