### ISSUE TITLE
Instant Payment Notification Settings

### ISSUE THREAD

**Issue by jaymoh** [knox2/Pesapal#23]
hi, So I have successfully integrated the Pesapal payment API thanks to this laravel package. My question is, which route do I add to the pesapal's IPN settings form. The route calling the payment's confirmation method in my controller(as in your example) i.e this one below

 ` public function paymentConfirmation(Request $request){
        $trackingid=$request->input('pesapal_transaction_tracking_id');
        $merchant_reference=$request->input('pesapal_merchant_reference');
        $pesapal_notification_type=$request->input('pesapal_notification_type');
        $this->checkpaymentstatus($trackingid,$merchant_reference,$pesapal_notification_type);
    }`

or the route calling the method in the PesapalAPIController in the package, i.e this one:

`function handleIPN()
    {
        if (Input::has('pesapal_notification_type') && Input::has('pesapal_merchant_reference') && Input::has('pesapal_transaction_tracking_id')) {
            $notification_type = Input::get('pesapal_notification_type');
            $merchant_reference = Input::get('pesapal_merchant_reference');
            $tracking_id = Input::get('pesapal_transaction_tracking_id');
            Pesapal::redirectToIPN($notification_type, $merchant_reference, $tracking_id);
        } else {
            throw new PesapalException("incorrect parameters in request");
        }
    }`

**Comment by jaymoh** [comment]
This is the form I mean:
![image](https://user-images.githubusercontent.com/3967097/55017529-fceb9e00-5001-11e9-9c3a-e395aa336154.png)

**Comment by knox2** [comment]
Create the route yourself and name it however you want, assign a controller to the route then set the controller method in the ENV e.g

PESAPAL_IPN=MyController@ipnResponse

**Comment by jaymoh** [comment]
I got that, what I'm not understanding is why the same method specified in **PESAPAL_IPN=MyController@ipnResponse** is being called in the method **redirectToIPN** but with different parameters, while I thought it should be accepting only the Request object since it's a route. Am I missing something? 
See below code it's in the Pesapal.php class 

`//UPDATE YOUR DB TABLE WITH NEW STATUS FOR TRANSACTION WITH pesapal_transaction_tracking_id $pesapalTrackingId
            $separator = explode('@', config('pesapal.ipn'));
            $controller = $separator[0];
            $method = $separator[1];
            $class = '\App\Http\Controllers\\' . $separator[0];
            $payment = new $class();
            $payment->$method($transaction_id, $status, $payment_method, $merchant_reference);`

**Comment by knox2** [comment]
I get your point, for the url of the route use /pesapal-ipn eg mysite.com/pesapal-ipn in pesapal, the package will handle the parameters from pesapal internally

**Comment by jaymoh** [comment]
Great, thank you. That means I update the method in my controller, i.e. the method initially referred to by this .env variable **PESAPAL_IPN=MyController@ipnResponse** from being a route to a function that receives parameters after being called from the **redirectToIPN** function and saves in the database. 

Its definition should be something like:

**function ipnResponse($transaction_id, $status, $payment_method, $merchant_reference){
}**

Would you kindly update that in the example for future users of this package? Thank you for the effort.

**Comment by knox2** [comment]
Thats correct, thanks for the suggestion. I'm gonna go ahead and close this

**Comment by jaymoh** [comment]
In case anyone encounters the maximum execution time reached, it's because of these lines: 

`if ($status == 'PENDING') {
                sleep(60);
                redirectToIPN($pesapalNotification, $pesapal_merchant_reference, $pesapalTrackingId);
            }`

Remember to update your php.in config files to increase execution time from the usual: **max_execution_time = 30**  to something like: **max_execution_time = 300**

**Comment by jaymoh** [comment]
The was breaking at this line **redirectToIPN($pesapalNotification, $pesapal_merchant_reference, $pesapalTrackingId);** with error: function not found. 

So I added **public** to the function declaration, and called the function with **$this** keyword.  Everything is working fine now. 

`public function redirectToIPN($pesapalNotification, $pesapal_merchant_reference, $pesapalTrackingId)
{
}`

then;
`if ($status == 'PENDING') {
                sleep(60);
                $this->redirectToIPN($pesapalNotification, $pesapal_merchant_reference, $pesapalTrackingId);
            }`

**Comment by knox2** [comment]
Hi, Kindly do a pull request then I'll review and test

**Comment by jaymoh** [comment]
Hi, I have done so. This is my first pull request on Github, let me know. Cheers!
