### ISSUE TITLE
Undefined index: scheme

### ISSUE THREAD

**Issue by nerdsome** [knox2/Pesapal#27]
There seems to be an error in the knox/pesapal/src/OAuth/OAuthRequest.php

    public function get_normalized_http_url()
    {
        $parts = parse_url($this->http_url);
        if (array_key_exists('port', $parts)) {
            $port = @$parts['port'];
        } else {
            $port = false;
        }

>         `$scheme = $parts['scheme'];`

**Comment by knox2** [comment]
What does the error say?

**Comment by KingStevenNOS** [comment]
is the at symbol meant to be there at `@$parts['port'];` ?? Seems abnormal

**Comment by knox2** [comment]
The symbol just means an exception won't be thrown by php if the index is not defined
