### ISSUE TITLE
passing details to iframe (Pesapal payment iframe not showing)

### ISSUE THREAD

**Issue by mulatha** [knox2/Pesapal#29]
When I use {{$iframe}} in view blade I get the following display instead of the intended Pesapal Iframe

`<iframe src="https://demo.pesapal.com/api/PostPesapalDirectOrderV4?amount=1000&currency=UGX&description=Enrolled%20for%20class%20at%20Schuline%20Learning%20Portal&email=Admin%40infouganda.net&first_name=Caniwia&height=400px&last_name=phoste&oauth_callback=http%3A%2F%2F127.0.0.1%2FeClass%2Fxul%2Fpublic%2Fpesapal-callback&oauth_consumer_key=wTrOMVGPOrbrQdIKCnh%2F0f%2FANg%2F7z2g6&oauth_nonce=%7B0157F6E6-9472-AC0C-4D04-2D9A73C03353%7D&oauth_signature=3z5wkOIq1f9vxRKgAtuD2hmEMHo%3D&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1593765358&oauth_version=1.0&pesapal_request_data=%26lt%3B%3Fxml%20version%3D%26quot%3B1.0%26quot%3B%20encoding%3D%26quot%3&phonenumber=256781463437&reference=PESAPALEA1BVMUE7ESDN9O&type=MERCHANT&width=100%25" width="100%" height="400px" scrolling="auto" frameBorder="0"> <p>Unable to load the payment page</p> </iframe>`

`PESAPAL_CONSUMER_KEY=2bNDTh8ial2........

PESAPAL_CONSUMER_SECRET=/9Tc.................

PESAPAL_CURRENCY=UGX

PESAPAL_IPN=PesapalController@paymentconfirmation

PESAPAL_LIVE=false

PESAPAL_CALLBACK_ROUTE=paymentsuccess`

If you could give me code and guide on how to add iframe I would really appreciate

**Comment by tha-ninja** [comment]
use this **{!! $iframe !!}** to render the html instead of {{$iframe}}.
