### ISSUE TITLE
iframe not loading

### ISSUE THREAD

**Issue by felixkaleke** [knox2/Pesapal#33]
![Capture](https://user-images.githubusercontent.com/61387033/194266155-a101003c-d328-4c6b-aaa3-f38405760a69.PNG)
This is what am getting instead of the iframe itself

**Comment by knox2** [comment]
Show the your twig

**Comment by felixkaleke** [comment]
<iframe src="https://demo.pesapal.com/api/PostPesapalDirectOrderV4?amount=10&currency=KES&description=Test%20Transaction&email=felixkaleke0%40gmail.com&first_name=Felix&height=100%25&last_name=Kaleke&oauth_callback=http%3A%2F%2Flocalhost%3A8000%2Fpesapal-callback&oauth_consumer_key=qkio1BGGYAXTu2JOfm7XSXNruoZsrqEW%2FscY&oauth_nonce=%7B9FFC5683-37E5-3362-9504-1E5A578BC127%7D&oauth_signature=y1w9VlV0W81I6i5i8J2Z3gCDBfM%3D&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1665049575&oauth_version=1.0&pesapal_request_data=%26lt%3B%3Fxml%20version%3D%26quot%3B1.0%26quot%3B%20encoding%3D%26quot%3Butf-8%26quot%3B%3F%26gt%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%26lt%3BPesapalDirectOrderInfo%20%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20xmlns%3Axsi%3D%26quot%3Bhttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchemainstance%26quot%3B%20%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20xmlns%3Axsd%3D%26quot%3Bhttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%26quot%3B%20%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20Amount%3D%26quot%3B10%26quot%3B%20%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20Description%3D%26quot%3BTest%20Transaction%26quot%3B%20%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20Type%3D%26quot%3BMERCHANT%26quot%3B%20%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20Reference%3D%26quot%3BPESAPALFDU1B7CW9BD2A4S%26quot%3B%20%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20FirstName%3D%26quot%3BFelix%26quot%3B%20%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20LastName%3D%26quot%3BKaleke%26quot%3B%20%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20Currency%3D%26quot%3BKES%26quot%3B%20%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20Email%3D%26quot%3Bfelixkaleke0%40gmail.com%26quot%3B%20%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20PhoneNumber%3D%26quot%3B254714825792%26quot%3B%20%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20xmlns%3D%26quot%3Bhttp%3A%2F%2Fwww.pesapal.com%26quot%3B%20%2F%26gt%3B&phonenumber=254714825792&reference=PESAPALFDU1B7CW9BD2A4S&type=MERCHANT&width=100%25" width="100%" height="100%" scrolling="auto" frameBorder="0"> <p>Unable to load the payment page</p> </iframe>

**Comment by felixkaleke** [comment]
thats what am getting in the pesapal.blade.php

**Comment by felixkaleke** [comment]
instead of dispalying the pesapal iframe  itself , {{$iframe}} in the view file , it bringa the above response

**Comment by knox2** [comment]
So your blade containts  {{$iframe}} ?

**Comment by felixkaleke** [comment]
yes my view contains {{$iframe}}

**Comment by knox2** [comment]
What does  {!! $iframe !!} produce?

**Comment by felixkaleke** [comment]
![image](https://user-images.githubusercontent.com/61387033/194326926-64ac840b-168b-4f34-97fd-02a8662324cb.png)
 the above image is what my view produce

**Comment by knox2** [comment]
send me a screenshot of your view

**Comment by felixkaleke** [comment]
![image](https://user-images.githubusercontent.com/61387033/194327776-b9e59413-0340-459b-951c-b2f29cc3474a.png)
please above is the screenshort of my blade view

**Comment by knox2** [comment]
replace {{ $iframe }} with  {!! $iframe !!}

**Comment by felixkaleke** [comment]
great thanks, i think i have an error with consumer key

**Comment by knox2** [comment]
Welcome....Will go ahead and close this

**Comment by felixkaleke** [comment]
![image](https://user-images.githubusercontent.com/61387033/194330090-ac9cb934-e5dd-42a5-b4fb-b34b88ae1345.png)
am getting still this and have inserted my key well,

**Comment by knox2** [comment]
This means, your key is not valid.....Are you using the correct environment, eg test

**Comment by felixkaleke** [comment]
![image](https://user-images.githubusercontent.com/61387033/194330954-9c7b7cb4-807f-40e6-a41d-711ded034169.png)
 this is my pesapal.php in config folder have inserted keys in .env file but still the key cant be found

**Comment by felixkaleke** [comment]
wanted to get clarification about the  ipn , the other things are working correctly but I still  dont update the records on the functions


    //u need to now query status..retrieve the change...CANCELLED? CONFIRMED?
    public function paymentconfirmation(Request $request)
    {
        $trackingid = $request->input('pesapal_transaction_tracking_id');
        $merchant_reference = $request->input('pesapal_merchant_reference');
        $pesapal_notification_type= $request->input('pesapal_notification_type');

        //use the above to retrieve payment status now..
        $this->checkpaymentstatus($trackingid,$merchant_reference,$pesapal_notification_type);
    }
    //Confirm status of transaction and update the DB
    public function checkpaymentstatus($trackingid,$merchant_reference,$pesapal_notification_type){
        $status=Pesapal::getMerchantStatus($merchant_reference);
        $payments = Payment::where('trackingid',$trackingid)->first();
        $payments -> status = $status;
        $payments -> payment_method = "PESAPAL";//use the actual method though...
        $payments -> save();
        return "success";
    }
}


please help me find the issue

**Comment by knox2** [comment]
This only occurs either when the key is incorrect or you are using a production key on a test environment and vice versa

**Comment by felixkaleke** [comment]
The payment is going through but seems the two functions arent working 
i mean the IPN function isnt working

**Comment by knox2** [comment]
have you set up the IPN in the env file?

**Comment by felixkaleke** [comment]
yes i have just set the way you have expained in the documentations
 PESAPAL_IPN=PaymentsController@paymentconfirmation

**Comment by knox2** [comment]
What's the IPN url that you have set in the pesapal portal

**Comment by felixkaleke** [comment]
http://localhost:8000/my-wallet/paymentconfirmation

This is the ipn url in the pesapal portal

**Comment by felixkaleke** [comment]
![WhatsApp Image 2022-10-11 at 08 54 59](https://user-images.githubusercontent.com/61387033/195009096-34b6e3d1-5913-4ab0-b2b5-88009edf0070.jpeg)

this is the screenshot

**Comment by knox2** [comment]
You cannot use localhost url on pesapal and as pesapal cannot access your localhost, url has to be visible on the internet

**Comment by felixkaleke** [comment]
ok great thanks let me , try in production site

**Comment by felixkaleke** [comment]
Have moved to production but still no response for the IPN function

**Comment by knox2** [comment]
Check pesapal logs for the error message if any

**Comment by felixkaleke** [comment]
Nothing important in logs ... only succesful payments ...my worry is why is the callback route functions well but the ipn functions not executing at all? , have even tried using ' App\Http\Controllers\PesaPalController@paymentconfirmation'  and the exact url that have registered in pesapal dashborad but still no changes

**Comment by knox2** [comment]
Reopen if still getting error
